name: CI

on:
  push:
  pull_request:

jobs:
  test:
    name: Build
    runs-on: macOS-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Build and Text
        run: |
          cd Example
          sh pod_install.sh
          xcodebuild -workspace Example.xcworkspace -scheme Example -sdk iphonesimulator
        env: 
         destination: ${{ matrix.destination }}
      - name: Update Code Coverage
        run: |
          bash <(curl -s https://codecov.io/bash) -J 'Example'

      - name: Update CocoaPods
        run: |
          cd ..
          sh auto_release_cocoapods.sh    
     
     